# Generated by Django 4.2.16 on 2024-10-28 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cargo_activo_categoriaexamen_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='usuario',
        ),
    ]
