# Generated by Django 4.2.16 on 2024-10-29 17:41

from django.db import migrations, models
import doctor.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_paciente_cedula_alter_paciente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cedula',
            field=models.CharField(max_length=10, validators=[doctor.utils.valida_cedula], verbose_name='Cédula'),
        ),
    ]
