# Generated by Django 5.1.2 on 2024-11-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_paciente_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='medicamentos/', verbose_name='Foto1'),
        ),
    ]
