# Generated by Django 4.2.16 on 2024-10-28 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attention', '0002_costosatencion_activo_horarioatencion_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citamedica',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='horarioatencion',
            name='doctor',
        ),
    ]
